
server:
  port: 9999

#Kafka Configuration
spring:
  kafka:
    bootstrap-servers:
        - localhost:9092
    producer:
      client-id: customer1
      bootstrap-servers:
      - localhost:9092
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer
      value-serializer:
        org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
             add:
               type:
                   headers: true 
    template:
      default-topic: timestamp
      


  
                   
#

#Kafka 
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.template.default-topic=Users                   
                   
#Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
#spring.kafka.template.default-topic    
#Topic Name    
                   