

server:
  port: 9990


spring:
  cloud:
    function:
      definition: numberConsumer;consumeAndProcessSqrt;consumeAndProcessCube;sqrtConsumer
    stream:
      bindings:
        numberConsumer-in-0:
          destination: numbers-topic
          
        sqrtConsumer-in-0:
          destination: sqrt-topic
          
        consumeCube-in-0:
          destination: cube-topic  

        consumeAndProcessSqrt-in-0:
          destination: numbers-topic
        consumeAndProcessSqrt-out-0:
          destination: sqrt-topic

        consumeAndProcessCube-in-0:
          destination: numbers-topic
        consumeAndProcessCube-out-0:
          destination: cube-topic

      kafka:
        binder:
          brokers: localhost:9092